<body>
  <script>
	$(function() {
	$( "#releaseDate" ).datepicker();
	});
  </script>
  
  <script id="bookTemplate" type="text/template">
        <div id="book-<%= id %>">
    		<img src="<%= coverImage %>"/>
    		<ul>
        		<li><%= title %></li>
        		<li><%= author %></li>
        		<li><%= releaseDate.date %></li>
        		<li><%= keywords %></li>
    		</ul>
			<button class="edit" data-id="<%= id %>">Edit</button>
    		<button class="delete" data-id="<%= id %>">Delete</button>
		</div>
  </script>
</body>
<h3>BookStore</h3>
<div id ="error" style="color:red;margin-bottom:10px;"></div>
<div id="books">
    <form id="addBook" action="#">
        <div>
<!--             <label for="coverImage">CoverImage: </label><input id="coverImage" type="file" /> -->
            <label for="title">Title: </label><input id="title" name="title" type="text" />
            <label for="author">Author: </label><input id="author" name="author" type="text" />
            <label for="releaseDate">Release date: </label><input id="releaseDate" name="releaseDate" type="text" />
            <label for="keywords">Keywords: </label><input id="keywords" name="keywords" type="text" />
            <input type="hidden" name="bookId" id="bookId" value="">
            <button id="add">Add</button>
        </div>
    </form>   
</div>